export default {
  total_distance: 0,
  average_distance: 0,
  total_elev_gain: 0,
  average_elev_gain: 0,
  total_moving_time: 0,
  average_moving_time: 0,
  count: 0,
  average_speed: 0,
  daysOfWeek: {
    1: 0,
    2: 0,
    3: 0,
    4: 0,
    5: 0,
    6: 0,
    7: 0,
  },
  periodOfDay: {
    earlyMorning: 0,
    morning: 0,
    afternoon: 0,
    evening: 0,
    night: 0,
  },
};
